[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 20
banaction = nftables-multiport
banaction_allports = nftables-allports
backend = auto
ignoreip = 127.0.0.1/8 ::1

[bareefers-nginx-limit]
enabled  = true
filter   = bareefers-nginx-limit
logpath  = /var/log/nginx/error.log
backend  = pyinotify
port     = http,https
maxretry = 10
findtime = 5m
bantime  = 2h

[bareefers-nginx-whatsnew]
enabled  = true
filter   = bareefers-nginx-whatsnew
logpath  = /var/log/nginx/access.log
backend  = pyinotify
port     = http,https
maxretry = 8
findtime = 3m
bantime  = 6h

[bareefers-nginx-botua]
enabled  = true
filter   = bareefers-nginx-botua
logpath  = /var/log/nginx/access.log
backend  = pyinotify
port     = http,https
maxretry = 6
findtime = 10m
bantime  = 24h

[bareefers-recidive]
enabled  = true
filter   = recidive
logpath  = /var/log/fail2ban.log
backend  = pyinotify
banaction = nftables-multiport
port     = http,https
findtime = 1d
bantime  = 1w
maxretry = 3
